### PR TITLE
Update kotlin version to 1.3.0

### PR DESCRIPTION
**Pull request by miga9**
As the title says, updated kotlin to 1.3.0.

### CODE REVIEW

**Comment by thauk-copperleaf** [comment]
Would recommend skipping 1.3.0 and going to the new bugfix release 1.3.10, since this hasn't been merged yet.

**Comment by miga9** [comment]
I updated it to 1.3.10 and squashed my commits.

**Comment by eivinwi** [comment]
Anything happening here? Would be nice to be able to upgrade to 1.3.10

**Comment by thauk-copperleaf** [comment]
> Anything happening here? Would be great to upgrade to 1.3.10

We're still using ktlint 0.25.0 and we're on Kotlin 1.3.10 and not seeing any difficulties, luckily.

**Comment by miga9** [comment]
@shyiko Hi, do you have plans for the new version soon?

**Comment by shyiko** [comment]
Sorry for the delay, @miga9. Merging in. I'll aim for a new release over the weekend.

**Comment by shyiko** [comment]
@miga9 It's getting late here so I'll have to move to Mon/Tue. I just want you to know that I haven't forgot about it and it's next on my todo list. Bear with me.

**Comment by miga9** [comment]
@shyiko No problem, there is no hurry. Thank you so much for looking into it.

**Pull request merged**
