### PR TITLE
Adding a flag to define the path for the .editorconfig file

### PR DESCRIPTION
**Pull request by bethcutler**
As discussed in issue #207

### CODE REVIEW

**Comment by bethcutler** [comment]
Just a quick note that this change is important to my project, and getting it into a release soon would really help me out.  Thanks!

**Comment by shyiko** [comment]
Merging in!

**Comment by shyiko** [comment]
@bethcutler [0.25.0](https://github.com/shyiko/ktlint/blob/master/CHANGELOG.md#0250---2018-07-25) is out

**Comment by bethcutler** [comment]
Great, thank you!

**Pull request merged**
