### PR TITLE
Fix unnecessary space between function signature and return type

### LINKED ISSUE #68: Flag unnecessary space between function signature and return type
I'd except the following code to get flagged since the scape before `:` is not needed:

```kotlin
interface Something {
  fun render(time: Long) : String
}
```

Instead, it should look like this:

```kotlin
interface Something {
  fun render(time: Long): String
}
```

Tested with `0.8.3` and `0.9.0`.

### PR DESCRIPTION
**Pull request by JLLeitschuh**
Closes #68

### CODE REVIEW

**Comment by shyiko** [comment]
Hi Jonathan. Thank you for the PR! Do you think you could change it a little bit to account for other cases (e.g. `fun fn(a: String, b : String) {}`)? It looks like https://github.com/shyiko/ktlint/blob/master/ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/SpacingAroundColonRule.kt#L21 can be used to derive a "stronger" condition - `val redundantSpacingBefore = node.prevSibling is PsiWhiteSpace && node.parent !is KtClassOrObject` (at least at first glance).

**Comment by JLLeitschuh** [comment]
In this example `fun fn(a: String, b : String) {}` which would be considered *correct*? Given the context of the PR I think probably `a: String`.

**Comment by shyiko** [comment]
That's right, `a: String` (https://kotlinlang.org/docs/reference/coding-conventions.html#colon). The rule of thumb: extra space added before ":" in type/supertype declarations, but it's expected to be omitted everywhere else.

**Comment by JLLeitschuh** [comment]
This now also covers reformatting this: `<T : PomModelAspect>`, to this: `<T: PomModelAspect>`

**Comment by shyiko** [comment]
It should `<T : PomModelAspect>`. As far as "whitespaces go", ktlint must be 100% compatible with IDEA's built-in formatter.

**Comment by JLLeitschuh** [comment]
Any hints on how to fix my existing code to make that work?

**Comment by shyiko** [comment]
@JLLeitschuh Sorry, I've been on the Internet with limited availability the last couple of days. I see you already took care of the generics. Is there anything else you want to do in this PR or that's about it?

**Comment by JLLeitschuh** [comment]
Nope, I'm happy with this PR as is!

**Comment by shyiko** [comment]
Thank you, Jonathan! Much appreciated :bowing_man:

**Pull request merged**
