### PR TITLE
CommentSpacingRule: Exclude //noinspection.

### PR DESCRIPTION
**Pull request by vanniktech**
Is there any magic that one needs to do in order to execute the tests?

`gradle test` didn't quite work.

### CODE REVIEW

**Comment by vanniktech** [comment]
Any reason why there are two build systems used here?

**Comment by shyiko** [comment]
@vanniktech Google's internal build infrastructure does not support Maven. Gradle scripts here are for their convenience. https://github.com/shyiko/ktlint/issues/102

**Comment by vanniktech** [comment]
Ah good to know. It's a pity for everyone who wants to contribute though as they're super confused - just like me.

**Comment by vanniktech** [comment]
Would it be possible to cut a new release with this?

**Comment by shyiko** [comment]
@vanniktech sure, I'll do it within the next couple of days.

**Pull request merged**
